box/urls.py
#_author: llm
#_date: 2019-04-01

from django.urls import path
from . import views

app_name = 'box'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('handle_login/', views.handle_login, name='handle_login'),
    path('index/', views.index, name='index'),
    path('logout/', views.logout, name='logout')
]

xyst_tools/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('box/', include('box.urls', namespace='box')),
]


urlpatterns += staticfiles_urlpatterns()

box/models.py
from django.db import models
# Create your models here.


# 用户权限表，存储 用户名、首次登录、上次登录、 用户权限 以及 是否激活状态
class User(models.Model):
    Username = models.CharField(max_length=50)  # 用户名
    firstLoginTime = models.BigIntegerField()  # 首次登录时间戳
    lastLoginTime = models.BigIntegerField()  # 上次登录时间戳
    privilege = models.SmallIntegerField(default=0)  # 0: 普通 1：编辑 2：管理
    isActive = models.BooleanField(default=True)  # 默认为激活

    # 返回用户的 username
    def __str__(self):
        return self.username


# 改进计划表
class Plan(models.Model):
    content = models.TextField()  # 计划内容
    owner = models.CharField(max_length=50)  # owner
    reviewer = models.CharField(max_length=50)  # reviewer
    expectFinishTime = models.BigIntegerField()  # 预期完成时间
    actualFinishTime = models.BigIntegerField()  # 实际完成时间
    createTime = models.BigIntegerField()  # 创建时间
    lastModifyTime = models.BigIntegerField()  # 最后修改时间
    createUser = models.ForeignKey(User, on_delete=models.PROTECT, related_name='plan_createUser')  # 创建者
    lastModifyUser = models.ForeignKey(User, on_delete=models.PROTECT, related_name='plan_modifyUser')  # 最后修改人
    finishStatus = models.BooleanField(default=False)  # 完成状态, 默认未完成
    isActive = models.BooleanField(default=True)  # 计划有效状态，默认有效

    def __str__(self):
        return self.content[:50]


# 问题表
class Problem(models.Model):
    title = models.CharField(max_length=200)  # 问题点
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT)  # 关联计划
    creatUser = models.ForeignKey(User, on_delete=models.PROTECT, related_name='prob_createUser')  # 创建人
    creatTime = models.BigIntegerField()  # 创建时间
    lastModifyUser = models.ForeignKey(User, on_delete=models.PROTECT, related_name='prob_modifyUser')  # 最后修改人
    lastModifyTime = models.BigIntegerField()  # 最后修改时间
    isActive = models.BooleanField(default=True)  # 默认存在

    def __str__(self):
        return self.title


# bug定级表
class BugLevel(models.Model):
    priority = models.CharField(max_length=20, unique=True)  # bug 级别 ，唯一
    description = models.CharField(max_length=50, unique=True)  # bug 描述， 唯一
    isActive = models.BooleanField(default=True)  # 决定是否展示

    def __str__(self):
        return self.description


# 故障原因/故障类型
class BugReason(models.Model):
    reason = models.CharField(max_length=50, unique=True)  # bug 产生原因
    isActive = models.BooleanField(default=True)  # 决定是否展示

    def __str__(self):
        return self.reason


# 故障来源
class BugSource(models.Model):
    source = models.CharField(max_length=50, unique=True)  # bug来源
    isActive = models.BooleanField(default=True)  # 决定是否展示

    def __str__(self):
        return self.source


# 业务线
class Line(models.Model):
    lineName = models.CharField(max_length=50, unique=True)  # 业务线，唯一
    owner = models.CharField(max_length=50)  # 业务线负责人
    isActive = models.BooleanField(default=True)  # 默认为 true

    def __str__(self):
        return self.lineName


# 平台
class Platform(models.Model):
    platformName = models.CharField(max_length=50, unique=True)  # 平台名称
    owner = models.CharField(max_length=50)  # platform负责人
    isActive = models.BooleanField(default=True)  # 默认为 True

    def __str__(self):
        return self.platformName


# 通知人
class NotiPeople(models.Model):
    username = models.CharField(max_length=50, unique=True)  # 通知人，唯一
    isActive = models.BooleanField(default=True)  # 有效的通知人

    def __str__(self):
        return self.username


# BugInfo
class BugInfo(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    startTime = models.BigIntegerField()
    endTime = models.BigIntegerField()
    influenceRange = models.BigIntegerField()
    influenceType = models.SmallIntegerField()  # 0: 用户数 ， 1： 请求数
    moreReason = models.TextField()
    process = models.TextField()
    owner = models.CharField(max_length=50)
    notifyType = models.SmallIntegerField()  # 0: 微信 1：邮件
    isNotify = models.BooleanField(default=False)  # 0:未通知  1： 已通知
    createTime = models.BigIntegerField()
    lastModifyTime = models.BigIntegerField()
    createPeople = models.CharField(max_length=50)
    lastModifyPeople = models.CharField(max_length=50)
    isActive = models.BooleanField(default=True)

    priority = models.ForeignKey(BugLevel, on_delete=models.PROTECT)
    lineName = models.ManyToManyField(Line, through="Bug2LineName")
    platformName = models.ManyToManyField(Platform, through="Bug2Platform")
    reason = models.ForeignKey(BugReason, on_delete=models.PROTECT)
    problem = models.ForeignKey(Problem, on_delete=models.PROTECT)
    bugSource = models.ForeignKey(BugSource, on_delete=models.PROTECT)
    notifyPeople = models.ManyToManyField(NotiPeople, through="Bug2NotiPeople")

    def __str__(self):
        return self.title


# Bug2LineName
class Bug2LineName(models.Model):
    bugID = models.ForeignKey(BugInfo, on_delete=models.PROTECT)
    lineNameID = models.ForeignKey(Line, on_delete=models.PROTECT)
    isActive = models.BooleanField(default=True)


# Bug2Platform
class Bug2Platform(models.Model):
    bugID = models.ForeignKey(BugInfo, on_delete=models.PROTECT)
    lineNameID = models.ForeignKey(Platform, on_delete=models.PROTECT)
    isActive = models.BooleanField(default=True)


# Bug2NotiPeople
class Bug2NotiPeople(models.Model):
    bugID = models.ForeignKey(BugInfo, on_delete=models.PROTECT)
    notipeople = models.ForeignKey(NotiPeople, on_delete=models.PROTECT)
    isActive = models.BooleanField(default=True)

box/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login  # 使用django内置的authenticate进行验证
from django.http import HttpResponse
from django.contrib.auth.models import User

# Create your views here.


def login_auth(func):
    def inner(request):
        is_login = request.session.get('is_login', False)
        if not is_login:
            return redirect('/box/login')
        else:
            return func(request)
    return inner


def login(request):
    return render(request, 'login.html')


def handle_login(request):
    if request.method != 'POST':
        return redirect('/box/login/')
    else:
        username = request.POST['username']
        password = request.POST['password']

        # # ldap验证: 因为前面已经配置过ldap， 所以这里会去和ldap的帐户进行验证
        # user = authenticate(username=username, password=password)

        # 解析 ldap cookie， 如果没有通过返回 login 界面

        # 通过验证，查询此账号是否在 box_user 中，不在的话 1。 添加新账号，并设定权限、创建时间和上次登陆时间 2。 设置cookie和session，并设置过期时间 3。 跳转到 index 页面

        request.session['is_login'] = True
        request.session['username'] = username

        return redirect('/box/index/')


def logout(request):
    # 如果有有效的 cookie 和 session，cookie 和 session 设置为过期
    try:
        # 将 session 置为失效
        del request.session['is_login']

        # ORM -----------> request.session.flush()  删除 django-session 表中的对应一行记录

    except KeyError:
        pass


    return redirect('/box/login/')


@login_auth
def index(request):
    if request.method == 'GET':
        cookie_content = request.COOKIES
        session_content = request.session

        print(cookie_content, session_content)

        return render(request, 'index.html')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 引入bootstrap -->
    <link href="{% static '/bootstrap-3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        .header .container-fluid{
            padding: 0px 20px;
        }
        .pull-right .dropdown-menu{
            min-width: 30px;
        }
    </style>
    {% block css %}{% endblock css %}
</head>
<body>
<div class="header">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">小 猿</a>
            </div>
            <div>
                <ul class="nav navbar-nav">
                    <li id="nav-list"><a href="#">故障列表</a></li>
                    <li class="dropdown">
                        <a id="nav-manage" href="#" class="dropdown-toggle" data-toggle="dropdown">管理<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">bug 配置管理</a></li>
                            <li><a href="#">权限管理</a> </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="pull-right" style="padding-right: 40px">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a id="nav-list" href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'box:logout' %}">退出登录</a> </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<div style="display: block;">
    {% block content %}{% endblock content %}
</div>



<div class="footer">
    <p>base</p>
</div>
<!-- jquery (bootstrap 的 js 插件需要引入 jquery -->
<script src="{% static '/jquery/jquery-3.3.1.min.js' %}"></script>
<!-- popper -->
<script src="{% static '/popper/popper-1.14.4.js' %}"></script>
<!-- 包括所有已编译的插件 -->
<script src="{% static '/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    box
{% endblock title %}

{% block content %}

{% endblock content %}

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login--</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 引入bootstrap -->
    <link href="{% static '/bootstrap-3.3.7/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .container{
            margin-top: 100px;
            width: 500px;
        }

        .form-control{
            display: inline-block;
            width: 400px;
        }

        .control-label{
            display: inline-block;
            width: 50px;
        }

        .form-group{
            margin-top: 30px;
            width: 500px;
        }

        .btn{
            width: 100px;
        }

        .msg{
            color: red;
        }
    </style>

</head>
<body>
<div class="container center-block" >

    <div class="row">
        <form class="form-horizontal" role="form" method="post" action="{% url 'box:handle_login' %}">
            {% csrf_token %}
            <h1 class="text-center">帐号登录</h1>
            <div class="form-group">
                <p class="text-center msg" >{{ message }}</p>
            </div>
            <div class="form-group">
                <label for="user_name" class="control-label col-lg-offset-1">用户名: </label>
                <input type="text" class="form-control " placeholder="请输入用户名" name="username">
            </div>
            <div class="form-group">
                <label for="pwd" class="control-label col-lg-offset-1">密码: </label>
                <input type="password" class="form-control " placeholder="请输入密码" name="password">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-success center-block" value="登录">
            </div>
        </form>
    </div>
</div>
<!-- jquery (bootstrap 的 js 插件需要引入 jquery -->
<script src="{% static '/jquery/jquery-3.3.1.min.js' %}"></script>
<!-- 包括所有已编译的插件 -->
<script src="{% static '/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
</body>
</html>